---
title: "Random Numbers and Random Number Generator"
date: "2023-05-22"
categories: [Julia, programming language, numerical analysis]
format:
  html: 
    code-fold: false
---

In social sciences, there are numerous cases of whether we need to use and generate random numbers, or draw random values from distributions.

- drawing from a sample: survey
- re-sampling: bootstrapping
- numerical analysis: integration, differentiation
- simulation: normal distribution

## Is Random Number Truly Random?

When we say truly random, these values cannot be repeated. Though it is more precise for the definition of random number, the process of generating random numbers is not reproducible. Therefore, we need pseudo-random numbers, which employs some specific algorithms to generate numbers, and usually requires a seed to recursively generate numbers.

### Random Number Generation vs. Random Number Generator(RNG)

Random number generation is the process of generating random numbers, while random number generator(RNG) serves a specific algorithm to generate random numbers. Most of time when we do numerical analysis, we use pseudo-random number generator(PRNG) instead of RNG.

In julia, there are two common algorithms of PRNG.

- Mersenne Twister algorithm
- xoshiro algorithm
- Lehmer algorithm

```{julia}
using Random, StableRNGs

## set random number seed
myrng1 = MersenneTwister(1234);
myrng2 = Xoshiro(1234);
myrng3 = StableRNG(1234);
```

### Put Random Seeds in "global" Scope

"Global" means it is visible (hence accessible) throughout the program, unless shadowed.

```{julia}
using Random

Random.seed!(1234)   # use julia's default RNG
Random.seed!(myrng1) # use myrng1 as RNG
Random.seed!(MersenneTwister(1234)) |> display
Random.seed!(myrng1, 5678) # overwrite the seed of myrng1
```

Now that we have set up our RNG, we can apply it to generate some random numbers using `rand()`.

```{julia}
using Random

Random.seed!(1234)

a1 = rand(4)
a2 = rand(4, 1)
a3 = rand(4, 2)
a4 = randn(4, 3)

@show a1
@show a2
@show a3
@show a4
```

Note that we can recognise RNG as a stopwatch. When the programme has finished generating some random numbers, the stopwatch will stop and reset. Hence you can check the result if you put another RNG before `a1` and see whether the result would be the same as what `a1` was.[^1]

[^1]: The answer is no, obviously. Therefore, that's the reason why we need to put `Random.seed!(1234)` in our script.

You might think what is the difference between `a1` and `a2`. We can use `size()` and `typeof()` to check.

```{julia}
@show a1
@show a2

# See the dim of a1 and a2
@show size(a1)
@show size(a2)

# Check the type of a1 and a2
@show typeof(a1)
@show typeof(a2)
```