---
title: "危機處理與外交政策(Crisis Management and Foreign Policy)"
date: "2023-06-04"
categories: [polisci, foreign policy]
---

## 危機處理的重要性：

以解決當前政策問題(policy problem)而非以制定長期政策方向為主的外交決策，往往都是在處理危機，有時間上的迫切性，以及並非常態性決策活動涉及的問題或情況。實際例子是，我國國家安全委員會議在處理與外交有關的決策部分，往往反映了上述這種持績性的以處理當前問題為主，不斷「救火」的型態。

## 外交決策與政策方面關於危機的簡單定義

危機是一種特殊形態的政策。政策問題是一種在行為者看來必須被改變的狀態或情勢，而其特殊性，反映在三個層面：

- 所威脅到的與該行為者有關的利益或目標：所威脅到的利益越重大，越接近典型的危機
- 危機出現後，在多久時間內，行為者必須產生針對解決危機之行為反應：時間愈短，愈接近典型危機
- 行為者無法預知危機出現的程度，亦即驚訝(surprise) 的程度：驚訝程度倉高，愈接近典型危機·

按照在上述三個面向上，程度是高或是低的區分，有八種排列組合，形成八種不同的危機類型：

1. 高威脅、時間短、高驚訝：典型危機情勢(typical crisis situation)——古巴飛彈危機、韓戰危機

2. 高威脅、時間長、高驚訝：創新性情勢(innovative situation)——冷戰形成時期英國於1947年2月通知美國無法再援助遭到國內共產勢力威脅的希臘與土耳其，因而產生十五週內完成的馬歇爾計畫；1956負要月埃及的Nasser將蘇伊士運河國有化

3. 低威脅、時間短、高驚訝：附隨性情勢(circumstantial situation)——1956年10月的布達佩斯抗暴·西方國家在11月中旬才反應

4. 低威脅、時間長、高驚訝：惰性情勢(inertia situation)——1959年 de Gaulle 命令法國地中海艦隊脫離北約組織的指揮體系：1964年10月15日 Khrushchev 忽然被迫下台

5. 高威脅、時間短、低驚訝：反射性情勢(reflexive situation)——第二次與第三次柏林危機；1958年台海危機

6. 高威脅、時間長、低驚訝：慎思性情勢(deliberative situation)——美國在1949年下半年預知中國大陸即將赤化以及東歐情勢持績惡化，促使 NSC68 號文件的產生

7. 低威脅、時間短、低驚訝：行政性情勢(administrative situation)——1962年10月印度與中國大陸發生邊界衝突，印度要求美國提供軍事援助，美國基於從當年5月起的研究與規劃，於一週內派遣艦隊到印度洋

8. 低威脅、時間長、低驚訝：例行性情勢(routinized situation)——外交決策者，針對經常性、循環性的情勢或問題，按照慣用的處理模式與SOP，做出反應，例如美國在1951年9月舊金山會議之前，處理與日本簽訂和約問題：台灣加入聯合國

## 人質危機：一種特珠的危機類型

1979年美國駐伊朗大使館人質危機為最經典的例子。J. Carter 政府處理危機的主要特徵如下：

### 排除以武力方式解法人質危機：

於11/6的國家安全會議中，決定先試行所有可能的和平方式，武力手段是最後選擇，但應懲罰伊朗違反國
際法的行為，使其最後的成本大於效益。同時，避免造成衝突層次不斷升高的軍事行動，避免陷入長期戰爭泥淖。11/17，伊朗釋放 13 位阿富汗裔美國人與婦女外交官後，開始威會要審訊美國人質，美國除警告伊朗外，並加派航空母鑑到印度洋，伊朗於是不再做類似威脅，也未再加害人質。此梭直到 1980/4，美國透過各種外交途裡，各種中間人或第三國，希望伊朗釋放人質，但均無效。1980/4/25，美國採取特種部隊軍事營救行動，但因為遭逢沙漢風暴，美國軍機自行相撞，而以失敗告終。美國放任新聞媒體日以繼夜報導人質危機，且為了因應危機而耗費過多行政資源，幾乎使得處理其他治理議題的功能為之癱瘓

### 一再對伊朗讓步但並未奏效

1979/11 欲派遣特使求見 R. Khomeini 但卻遭拒；1979/12/15，迫使 P 離開美國而前往巴拿馬居留；1980/2，伊朗要求聯合國成立調查團，調查 P 以往在伊朗的不法行為，美國原先欲以此為條件換取釋放人質卻遭伊國拒絕後，仍不反對聯合國成立調查團，Carter 宣稱對於美伊兩國過去的誤解而表示歉意；同年 3 月，美國促使巴拿馬與伊朗兩國政府談判引渡 P 回伊朗，藉此交換美國人質，P 知情後匆忙於 3/23 飛往埃及；1981/1/20，美伊兩國達成協議，美允諾日後不干涉伊朗內部事務、伊朗可依法調查 P 在美資產、不追訴伊朗人員綁架美國人質的法律責任。

### 實施多項制裁但並未奏效

1979年實施的制裁，包括伊朗的武器禁運、停購伊明石油、凍結伊朗在美資產、驅逐部分伊朗駐美外交官、上訴國際法院並獲得伊朗行為屬非法的判決、UN 安理會全栗通過要求釋放人質否則施以經濟制裁。1980 實施者有與伊朗斷交，以及對伊朗進口到美國的所有貨品實施抵制。

### 為何 Carter 政府始終軟弱且避免訴諸武力

主要原因在於當時特殊的民意趨勢與社會氛圍使然，且 Carter 總統本身標舉所謂「人權外交」。










