---
title: "領導者與民主制度"
image: polisci preview.svg
lang: en
description: |
    領導者是否重要？又，如何以統計的方式驗證上述問題？
date: "2023-07-24"
draft: FALSE
citation:
  url: https://yueswater.netlify.app/posts/2023-07-24-politcal-economy-leaders-and-democratic-institutions/
categories: [macroeconomics]
---

> "*The historians, from an old habit of acknowledging divine intervention in human affairs, look for the cause of events in the expression of the will of someone endowed with power, but that supposition is not confirmed either by reason or by experience.*"
> <p style="text-align:right;">------Leo Tolstoy</p>

> "*There is no number two, three, or four $\cdots$ There is only a number one: that’s me and I do not share my decisions.*"
> <p style="text-align:right;">------Felix Houphouet-Boigny, President of Cote D’Ivoire (1960-1993)</p>

## 領導者真的重要嗎？

為何領導者在一個政治體制內是重要的？領導者在人類歷史上扮演重要的角色，從部落時期的酋長，到歐洲封建時期的領主、華夏文化的皇帝，乃至於當今社會的總統、總理等，這些都是領導者。

有人說領導者之所以重要，是因為領導者可以作出決定(make decisions)、制定政策(make policies)、簽署法案(sign laws)等，但是這些答案都並未回答到上述的問題。如果從政治學的角度觀之，我們可以說領導者的重要性仰賴於其可以「安內攘外」——內部作為制衡的角色，外部作為主權的象徵，避免外患入侵國家。

### 模型設定

為了檢證領導者是否重要，實證上我們可以在領導者這個變項上做出一些變動，端看這些改變是否會影響到政治或經濟表現(political or economic outcome)。

因此，我們會需要以下的變數幫助我們釐清上述問題。

- 「表現」變數：學理上我們稱之為被解釋變數(dependent variable)，因為這是我們想要探討的結果。經濟成長指標即是一個很好的變數，我們可以透過 GDP 平減指數作為變數。
- 「解釋」變數：解釋變數(independent variable)也就是用來解釋表現的變數，例如我們可以在領導者這個變數上動一些手腳，多半都是統計上的處理方式。

統計學上我們可以將上述的關係寫成數學的形式：
$$
\mathbf{y} = \mathbf{x}\boldsymbol\beta + \boldsymbol\varepsilon
$$
其中 $\mathbf{y}$ 即是被解釋變數，$\mathbf{x}$ 為解釋變數，$\boldsymbol\beta$ 為係數(coefficient)，而 $\boldsymbol\varepsilon$ 則是一些無法解釋、沒辦法觀察到的因素。

### 理解「變異」

通常我們會要求解釋變數具有變動，否則如果這些變數永遠都停留在原本的位置，就無法繼續深入研究這些變數對於政治或經濟表現有何影響。

回到原本的議題，我們現在將領導者的定義縮小範圍，僅聚焦在民主國家的「總統」(president)上。根據實證研究，總統在經濟表現極差的時候，多半會在選舉中慘敗。

## 論文探討與統計方法介紹

Ben Olken 針對其文章 ["*Hit or Miss? The Effect of Assassinations on Institutions and War*"](https://www.aeaweb.org/articles?id=10.1257/mac.1.2.55) 進行導讀。其核心概念是試圖找出一個「乾淨」（外生）的領導者變異；也就是說，其是一種看似像是隨機實驗的變異。這些變異通常被稱為「自然實驗」(natural experiment)。

在這些研究中，學者們關注的是特定事件（如刺殺）或歷史時期對領導者的變動是否可以被視為一種不受人為影響的變化，而且能夠為研究領導者對社會、政治和經濟影響的因果關係提供更為客觀的證據。

「刺殺」(assassination)提供了一種類似於隨機實驗的方式來改變領導者：未遂的刺殺作為成功刺殺的對照組。例如，比較 John F. Kennedy 的刺殺與對 Ronald Reagan 的刺殺企圖。子彈奪去了 JFK 的生命，而差幾吋的距離讓里根得以倖免於難。

透過研究刺殺事件，我們或許可以找到一個具有隨機性的變動，進而探討在領導者變更時，對於社會和政治的影響。成功和失敗的刺殺案例，將形成一個有趣的比較，幫助我們了解領導者的重要性以及他們所扮演的角色對於國家穩定和經濟發展的影響。

### 刺殺事件與政治體制

為了了解更換領導人是否有所影響，我們對刺殺事件i進行估計迴歸分析，表達如下：
$$
y_i = \beta{SUCCESS_i} + \varepsilon_i
$$

其中，$y_i$表被解釋變數，例如刺殺事件前一年到五年後的民主程度變化，$SUCCESS_i$ 表示一個虛擬變量(dummy variable)，若領導人被殺則為 $1$，若倖存則為 $0$，即
$$
SUCCESS_{i} =
\begin{cases}
1, \quad \text{if killed}\\
0, \quad \text{if survive}
\end{cases}
$$
$\varepsilon_i$ 表示誤差項，$\beta$ 表示成功刺殺對 $y$ 的平均影響。

在這個簡單迴歸中，$\hat{\beta}$ 代表了成功刺殺和失敗刺殺時 $y_i$ 的差異，即：
$$
\hat{\beta} = \mathbb{E}[y | SUCCESS = 1] - \mathbb{E}[y | SUCCESS = 0]
$$
藉由這樣的分析方法，我們可以評估刺殺事件是否對於影響政治體制產生顯著的效果。

#### 統計上的假設

在這個理論中一個重要的假設是：

$$
y_i = \beta{SUCCESS_i} + \varepsilon_i
$$

在進行這樣的迴歸分析時，其中一個關鍵假設是誤差項 $\varepsilon$ 和虛擬變量 $SUCCESS$ 之間是不相關的。

我們可以計算
$$
\hat{\beta} = \mathbb{E}[y | SUCCESS = 1] - \mathbb{E}[y | SUCCESS = 0]
$$

將這個結果中的 $y$ 以 $y_i = \beta{SUCCESS_i} + \varepsilon_i$ 取代，得到

$$
\hat{\beta} = \beta + \mathbb{E}[\varepsilon | SUCCESS = 1] - \mathbb{E}[\varepsilon | SUCCESS = 0]
$$
因此，我們需要假設 $\mathbb{E}[\varepsilon | SUCCESS = 1] = \mathbb{E}[\varepsilon | SUCCESS = 0]$，即 $\varepsilon$ 與 $SUCCESS$ 無相關。

這個假設的重要性在於，其確保了估計結果的一致性和有效性。如果誤差項與虛擬變量之間存在相關性，那麼迴歸結果可能會出現偏誤，使得我們無法正確地衡量成功刺殺對因變數 $y$ 的影響。

#### 實務上的解釋

$$
y_i = \beta_{SUCCESS_i} + \varepsilon_i
$$

假設 $y$ 是一個代表「在刺殺事件前一年和事件後間成為民主國家」的變數。在這種情況下，$\varepsilon$ 和 $SUCCESS$ 不相關的意思是：這表示刺殺事件的成功與否不會因為該國本來就會轉變成民主國家而更有可能發生。

舉例來說，在伊拉克戰爭前夕，美國試圖刺殺 Saddam Hussein。假設美國非常努力地試圖刺殺 Hussein，因為他們知道如果刺殺失敗，他們將會發動戰爭將他剷除。

但我們怎麼知道 $\varepsilon$ 和 $SUCCESS$ 是不相關的？答案是：我們無法直接檢查。這是一個假設。不過我們可以嘗試思考其他可能的推論。特別是，我們可以檢查我們認為與 $y_i$ 相關的其他變數是否與 $SUCCESS_i$ 不相關，這可以幫助我們在某種程度上確認識別性假設是否合理。

#### 控制變數

Olken 發現使用槍支進行刺殺的成功機率比使用炸彈更高：使用槍支需要更加專注的刺客，因為開槍被抓到的風險比安置炸彈更高。因此，也許在本來刺殺事件後國家更有可能轉變成民主國家的情況下，更容易使用槍支。

如果上述的假設是肯定且正確的，我們可以對槍支這個變數進行控制：
$$
y_i = \beta{SUCCESS_i} + \gamma{GUN} + \varepsilon_i
$$

現在的假設是，在我們考慮是否使用槍支的情況下，誤差項 $\varepsilon$ 與成功與否 $SUCCESS$ 是不相關的。例如，我們比較使用槍支的成功事件與使用槍支的失敗事件之間的影響，以及沒有使用槍支的成功事件與沒有使用槍支的失敗事件之間的影響。這樣的控制變數方法可以幫助我們在某種程度上確保研究結果的準確性，並排除因槍支使用造成的偏誤。

我們認為已經很好地隔離了問題的源頭，即槍支使用更容易成功，並且可能與
$y$ 相關，控制變數是有幫助的。這可以幫助我們排除槍支使用對結果的影響，並確保研究結果的準確性。但是一般而言，在研究設計中，沒有任何東西可以取代創造虛擬隨機性的良好研究設計——即知道變異來自哪裡，並且可以根據統計原則評估假設是否與結果無關。

假設我們將成功的刺殺年份與所有其他年份的所有國家進行比較。這樣的比較並不是一個好的方法。原因是，這種比較並沒有創造出真正的隨機性或對照組。在這種情況下，可能存在許多與刺殺和民主化之間相關的因素，這會導致我們無法確定是否僅僅是刺殺對民主化的影響。

綜上，我們在研究時應該努力設計良好的實驗或隨機對照試驗，或者使用其他控制方法，確保所得結果的可靠性和有效性。

在這個研究中，我們限定在「強烈的刺殺意圖」，即槍支開火、炸彈爆炸等情況下進行分析。我們進行迴歸分析如下：

$$
y_i = \beta{SUCCESS_i} + \gamma{WEAPON_i} + \varepsilon_i
$$

其中 $WEAPON_i$ 是數個虛擬變數，分別代表不同的武器類型。

該研究主要研究國家民主程度的變化，使用 [Polity 資料集](https://www.systemicpeace.org/polityproject.html)將所有國家自 1875 年以來歸類為專制（設定為 $0$）或民主（設定為 $1$）。觀察是否有變化以及是否存在正向關係。

另外，我們使用 A[rchigos 資料集](http://ksgleditsch.com/archigos.html)觀察領導人的過渡，將其歸類為常規（選舉）或非常規（政變），然後看在接下來的 20 年中，有多少百分比的領導人過渡是常規的。

同樣，我們觀察衝突的變化，使用 [COW 資料集](https://correlatesofwar.org/data-sets/)分類每年死亡人數超過 $1000$ 人的衝突，以及 [PRIO 資料集](https://www.prio.org/Data/)分類每年死亡人數在 $25$ 至 $1000$ 人之間的衝突。

### 統計方法：標準誤假設檢定

在估計上述迴歸方程式時，除了估計 $\hat{\beta}$ 之外，我們還需要知道估計結果的精確程度。因此，我們透過計算 $\hat{\beta}$ 的標準誤，記為 $\sigma$，檢證精確程度。

標準誤差(standard error)是我們對 $\hat{\beta}$ 估計值周圍的標準偏差。換句話說，假設我們重新運行了 $100$ 次實驗，並每次收集數據，$\hat{\beta}$ 的標準誤差反映了這 $100$ 次估計結果的標準差。

#### $\hat{\beta}$ 的分佈

假設我們有一個以 $\hat{\beta}$ 為中心，標準誤差為 $\sigma$ 的常態分配，即
$$
\boldsymbol{\hat{\beta}} \sim N(\pmb{\beta}, (\mathbf{X}^T\mathbf{X})^{-1}\sigma^2)
$$
#### 假設檢定

一個統計檢定的形式如下：
假設我有一個虛無假設(hypothesis testing)，即 $H_{0}:\beta = \beta_0$。進行檢證的方式是，假設真實情況是 $\beta = \beta_0$，且標準誤差為 $\sigma$，那麼已知 $\hat{\beta}$ 的分佈下，即可透過假設檢定驗證[^1]。如果我們能夠拒絕 $\hat{\beta} = 0$，我們就說 $\hat{\beta}$ 在統計上顯著。

[^1]:這裡就不贅述，就假設已經知道如何檢定。

其中，我們將 $\beta^* = \beta_0$ 給定我們的估計 $\hat{\beta}$ 的機率定義為顯著水準。通常我們使用 $5\%$的顯著水準，但有時也使用 $1\%$ 或 $10\%$。在大多數情況下，如果 

- $\hat{\beta} > 1.96\sigma$，我們可以在 $5\%$ 的水準上拒絕虛無假設

- $\hat{\beta} > 1.65\sigma$，我們可以在 $10\%$的水準上拒絕虛無假設。

#### 信賴區間

信賴區間是在顯著水準上無法拒絕的虛無假設的範圍，通常是 
$$
[\hat{\beta} - 1.96\sigma, \hat{\beta} + 1.96\sigma]
$$






















