---
title: "政府政治模型(Government Politics Model, GPM)"
date: "2023-06-02"
categories: [polisci, foreign policy]
---

政府政治模型有別於 RAM 與 OBM，雖其與 RAM 一樣重視政策制定而非執行的環節，但認為大部分外交決策的主要行為者並非單一行為者，而是包含來自不同政府部門的代表，或再加上政府以外的行為者，共同進行決策。一般來說，越是傾向權力分立制衡的政體，越有可能是適合以此種模式分析其實際決策過程。此外，GPM 認為經由此種過程產生的決策，**未必完全反映在國家利益層是成本最小、效益最大的選項**，而是**不同政府部門間互動**的結果。

政府中的每個人都是核心競爭賽局的參與者之一，此賽局即是政治。政府的行為因此得以依照 GPM 加以理解，非組織性的產出，而是議價賽局(bargaining game)的結果，眾多行為者都被視為是參與者，結果透過相互競爭偏好的互動而形成與消解。

## GPM 的基本概念

### 行為者

主要是參與決策當中來自不同官僚部門的代表，分為四種主要類型：

1. 首腦(chiefs)：指總統與部級的主管，包含總統、國務卿、國防部長 $\cdots$。
2. 幕僚(staffs)：指首腦所直接指揮的幕僚
3. 部眾(indians)：合議共治的群體，指各行政部門政務官與高階常任文官。
4. ad hoc players：臨時或隨機性參與者，如遊說團體、媒體、重要國會議員等。


### 決策過程的本質

是由以上不同行為者所参奥的一場賽局或議價賽局，決策的產出反映了賽局的結果。

### 不同行為者之間的差異

1.目標與利益：各自代表其本身官僚部門的組織目標或利益。
2.影響力、權力賽局的不同参與者，由於以下幾種條件的不同，使其在
能影響、改變他人行為選择的強弱程度也不同一組織中制度性高低、擁有資訊量的性質和多寡、個人的知識與能力、在特定議政策聯盟的籌碼和能力，包括溝通和說服的能力。

### 行動管道(action channel)

指將參與者的目標與影響力,帶到決策環節的一套制度化規則和程序，例如特定議題通常纳入的特定參與者型態、議事和決策的程序、相關的規範、部門間雙邊或多邊協商的既定模式。

### 決策的規則(decision rules)

當持有不同偏好、目標，影響力不同的多個行為者共同進行決策時，如何生最後的政策退項？

1.共識決：即一票否決制
2.首長制：参與者各自表達其偏好與發挥影響力後,由首長裁示。
3.投票表决：相對多數決·絕對多數決・多數的意見，有時未必經由正式
的投票表決程序來影響決策結果，也有可能透過結合為多數的聯盟(coalition)而使其能說服,強制、議價的能力增加，影響其他參與者的行為。

這裡要提到一個定理：**Arrow 不可能定理(Arrow's Theorem of Impossibility)**。該定理稱，持有不同偏好的個人，可能無法經由民主投票的多數決規則，來產出符合大多數人的集體偏好。

| 行為者 | 選項排序 |
|--------|----------|
| $A$      | $a>b>c$    |
| $B$      | $b>c>a$    |
| $C$      | $c>a>b$    |


其中行為者 $A$，其喜歡 $a$ 的程度多於 $b$；行為者 $B$，其喜歡 $b$ 的程度多於 $c$；行為者 $A$，其喜歡 $c$ 的程度多於 $a$。由於行為者的偏好具有遞移性(transitivity)，既然$c$ 多於 $a$ ，但在 $b$ 多於 $c$ 的前提下，$a$ 又大於 $b$，明顯出現矛盾，無法找到符合多數決的決策。

多數人一同決策時，意見往往是最重要的，民主政治的基本前提是決策必須符合多數人偏好。然而，Arrow 發現在某些特定條件下，例如行為者偏好之遞移性，將使得民主政治無法實現，無法找到符合多數決的決策。

因此，程序上的安排就顯得極為重要，議案提出的順序對於結果就有決定性的影響。議程設定(agenda setting)在多數表決時係十分關鍵，就算在相同偏好下，也會得到不同的結果，因此程序委員會扮演掌握議案生殺大權的重要角色，影響何種結果最後會勝出。

此定理指出，偏好的排序將會受到扭曲，或某些成員的偏好將凌駕於其他人的偏好上。

> 勿將個人特質賦予團體之上。個人是理性的，團體則否，因為團體可能甚至沒有可傳遞的順序偏好。

### 議題的塑造項(alternatives)

一個政策嫩題往往涉及或影響多種不同的杜會償值或規範，當某種價值或規範被特別強調放大時,往往有利於某些官僚部門的影響力擴大，不利於其他部門。之所以有利，還是因為影響力的大小涉及到需要用有顯性或隱性的聽眾(audience)。因此，媒體往往透過議題塑造，帶來重大影響。

議題的塑造(framing)係指特定的價值層面被塑造時，會出現特別的聽眾，如一般民意支持者、議員的支持，因此行為者便需要思考如何運用媒體凸顯某一個議題的某項特質。

### 合力(resultant)

決策的結果是一個由不同參與者產生的合力。例如很多國家都在發展武力，拜登用政府投入資金的力量去發展人工智慧，這是川普沒有的，川普只是禁止華為但並未投入特別資金在科技發展上。

### 團體迷思(Groupthink)

若團體中有一兩個人意見較為強烈，大家便會屈從少數一兩個人表達的意見而形成一言堂，儘管大家都有意見，但不願表達。最常見的狀況是在外交決策上，因為制度性權力的因素，從而導致此問題，例如 JFK 在 ExCom 的議題上。


## 以 GPM 解釋古巴飛彈危機

### 美國 U-2 偵察機發現蘇聯部署飛弹的過程：

如果美國發現的時間，提早了兩週，則當時蘇聯尚未將大部分飛彈組件運送完成，對美國形成安全威有的危機便不致出現。其實美國有機會更早透過 U-2 發現蘇聯運送的是彈道飛彈，關鍵是美國本身拖延了派出 U-2 的時間。

9 月中旬，隨著越來越多情報，顯示蘇聯有可能選送攻繁性武路到古巴，美國政府成立了一個路部門團隊，名為空中偵查委員會(COMOR)，規劃派遣 U-2 偵察機進行偵查。COMOR 當中，不同官僚部門那門之間的拉鋸，使得 U-2 偵察機派出時間有所延誤。

### ExCom 決定如何處理蘇聯飛彈的過程：

#### 初期來自不同官條部門的代表所各白持有的偏好和立場

1. 参謀首長聯席會議主席 Maxwell Taylor ：主張以空襲作為優先處理手段。而空襲的範園則是摧毀飛彈基地以及蘇聯的防空飛彈與轟炸機、戰門機。
2. Dean Rusk 國務卿認為，任何與他國之間關係的相關問題，包括可能形成軍事衝突的問题，首先應採取外交手段處理，唯有外交途徑無法解決時，才感該訴諸共他途徑。他建說直接與 Castro 對談，警告他蘇聯的作法讓古巴陷入危險，以及蘇聯可能為赢得柏林而出賣古巴。
3. MCNamara 不認為蘇聯的部署會影響到整個核武力量的對比，他甚至質疑軍事行動的必要性。其次，他認為貿然空襲可能影響選民對總統的支持，不利於總統的聲望。他也在一開始就提出封鎖(blockade)的選項。
4. 國家安全顧問 McGeorge Bundy，在整個決策過程中，他時常改變其看法，顯示似乎並無定見。支持作為總統的個人幕僚，其職務上的角色是支持少數意見，來維持總統做選擇的最大開放性。
5. RFK 不是由於制度性職務角色，而是總統胞弟關係參奥決策，他要傳達並強化總統的個人想法，並協助總統因應終和不同意見的壓力。
6. 其他參與者：駐聯合國大使 Adlai Stevenson 贊成 MNamara 的懷疑
論。McCone 支持 Taylor 的空聚方案。前任國務卿 Dean Acheson 贊同空襲，但他認為必須鎖定在空襲飛彈基地的範圍，而不攻擊蘇聯的轟炸機、防空部隊等，Bundy 支持此一看法。

所以，初期的意見分布，包括了空襲、外交、封鎖三種，各有不同的支持者。

#### 10月18日以後的發展一JFK 加入表達其偏好以後

JFK否決空襲的選項：在 ExCom 討論過程中，發現空襲難以做到控制規模與精準度，而必須實施大範圍的打擊，提高傷害程度，增加了衝突層次升高甚至走向核戰的機率，也恰巧跌入蘇聯解決柏林問題的陷阱。同時，JFK 認為空襲必然採用不宣而戰的方式，但不宣而戰正是日本當年在偷襲珍珠港的作法，會帶來重大的道德瑕疵，JFK 作為政治領袖無法接受此種有損政治聲望與道德形象的作法。

此時，檯面上只剩下封鎖的選項，但兩位参與 ExCom 的蘇聯事務專家，擔任無任所大使的 Bohlen 與 Thompson，提出最後通牒(ultimatum)的建議，認為該方法一方西可以對蘇聯時間施加壓力(尤其是deadline 上的壓力），另一方面卻也給予其考慮的時間。財政部長 Dillon 則提出，結合最後通牒與封鎖兩個選項，亦即一方面發出通牒，另一方面同時實施封鎖，使最後通牒變成有強制手段作為後盾的外交手段。

10月19日，JFK 與 Joint Chiefs of Staffs 會面，發現 JCS 仍堅持立即空襲古巴。空軍参謀長 Curtis LeMay，在國會作證時談到應採用空襲，受到國會支持，基於國會和民意的 支持(ad hoc player 也可能發揮影響），於是 LeMay 大膽直接挑戰 JFK，表示封鎖與政治行動只是如同在慕尼黑的姑息政策一樣，最終還是會引起戰爭。JFK 受到挑戰後，没有出席10/19 的會議，讓 RFK主持會議。10/19的會議中，一方主張封鎖(或再加上通牒），一方主張立即空襲。空襲派獲得了更多支持：Bundy 以及原來主張封鎖與通煤結合的 Dillon。但 Robert Kennedy 堅持 JFK 的原則：和珍珠港事件如出一轍的偷襲，不符合美國的對外政策傳統。

此時，官僚部門間的拉鋸陷入僵局，Rusk 提議，將所有成員區分成不同的小組，重新推敲這兩個方索。經過數小時的討論後，MoNamara 提出「封鎖加談判」的方案，他認為美國至少必須放棄其在土耳其與義大利的 Jupiter 飛彈基地，才能讓蘇聯改變其部署。針對封鎖加談判，RFK 並不贊成此種看來妥協更高的方案，顯示如果他代表 JFK 意見，則 JFK 一方面不希望因為空襲升高武力衝突，另一方面卻又不願被對手或國內認為過於軟弱妥協。此時，檯面上的選項其實都被代理 JFK 的 RFK 所否決了：空襲有道德問題且太冒險，封鎖加談判又太軟弱；討論陷入了進退維谷的困局。

第二天 10/20 的討論開始，又回到空襲和封鎖加談判兩種選項的競爭局面，MeNamara 介紹該選項時，提到他反對將最後通牒的條件設定在蘇聯必須撇除飛彈，他認為如此做是將蘇聯逼到牆角，增加其冒進的可能。他的意見得 Stevenson 支持。而 Taylor 則又再度提出空襲的必要，同時強烈建議時間不多，最遲必須在 10/22 發動空裝。在這個關頭，RFK 提出另一種綜合性的選項，即是封鎖＋最後通牒＋空襲，前二者同時實施，若蘇聯不撤除飛彈，則發動空襲。RFK 指出，此一選項的優點在於**不致產生奇製所衍生的道德問題**。原來支持軍方所提出空襲選項的 Dillion 與 McCone，都支持此一新選項。Dillion 建議，提出最後通牒到實施空襲，以間隔72小時為佳。

Rusk 提出一個所調另一個選項：凍結古巴島上的現狀，亦即不要讓蘇聯飛彈增加，以及拆除飛彈基地時，應請聯合國介入監督。當 RFK 在決策僵局打開突破口後，JFK 馬上抓住時機進行裁決式的陳述，他首先強烈反對封鎖加談判，理由是顯得太過軟弱，未必會讓蘇聯願意撤飛彈。他接著表示贊成實施封鎖加最後通牒，若不成功則發動空襲。但其認為發動空襲的必要前提是將打擊範圍限縮在飛彈基地本身，以及在 10/23 完成空襲的準備。當天會議就在暫無強烈反對意見下達成決策。決策中關於封鎖的原則(例如指封鎖載運武器的船隻)也隨之一併確定。

次日 10/21 開會時，主通是討論 Sorenson 在聯大的演說內容，如何向全球宣布美國的此一決策。JFK 強調，演說內容應表強硬立場，將重點放在強調蘇聯必須撒除飛彈，美國不怕發生武力衝突，而不表達任何交換的想法，其意見獲得贊成封鎖加最後通牒，以及必要時最後應實施空襲的 Dillion、McCone 、Thompson 等人支持。然面，當 McNamara 提出，必須先討論完如果必須賞施空製的整體計畫時，JFK 卻只回覆，其重點不在於強調空襲，而是在於要蘇聯拆除在古巴裝設的飛彈。

#### 蘇聯最後決定撤除飛彈前美蘇之間的互動

Sorenson 在聯合國演講以及 JFK 給 Khrushchev 的公開信，都強調三個重點：**必須拆除飛彈**、**所有攻擊性武器都必須拆除**、**拆除過程應在 UN 的有效監督和安排下為之**。針對 Khrushchev 先前曾寫信給 JFk，要求美國撤除在土耳其和義大利飛彈的部分，公開信中提到：若蘇聯接受撤除飛彈的要求，則對於其他地區之武力安排如何達到雙方接受的協議，美國會進行努力。

公開信發出後，JFK 召集 ExCom 中的少數成員，在白宮辦公室繼續討論與蘇聯大使 Dobrynin 的溝通，這部分的結果成為最後讓蘇聯讓步的關鍵作法之一。討論結果，決定和 Dobrynin 的溝通，是兩人面對面的口頭溝通，而非正式談判，不採用書面文字留下紀錄的溝通。溝通訊息的重點在於：只要蘇聯撤除飛彈，美國不會進攻古巴。同時，美國無法立即達成撤除在土耳其、義大利飛彈的協議，因為這牽涉到 NATO 內部的整體同意程序，需時較長。

於是 RFK 與Dobrynin會面，RFK 強調，兩人談話的內容如果洩漏，美國一概不承認。而在面對面的溝通中，RFK 不是只提供撤除美國飛彈的胡蘿蔔(carrot)部分，其實他更強調大棒(stick)部分——強調能解決的時間已經不多。由於古巴的蘇聯防空飛彈在10／27擊落了一架美國U-2，駕駛員殉職，在時間壓力下必須儘快解決。

Dobrynin 將口信傳給莫斯科，Khrushchev 面臨重要的抉擇。10／28 早上，Castro 打來電報，提到其研判美軍會在24-72小時內發動對古巴攻擊。攻擊可能是大規模空襲，也可能是地面進攻更提出，如果古巴受到攻擊，請 Khrushchev 考慮是否應動用核武。10／28中午，Khrushchev 召開最高蘇維埃會議，他向成員表示，蘇聯必須考慮發生武力衝突的後果，這種後果可能是摧毁全人類，為了顧及整個人類的命運，蘇聯必須讓步，必須接受美國的要求。當然，Khrushchev 也說明了美國承諾未來撤除飛彈的消息。到莫斯科時間下午兩點，透過公開廣播，蘇聯宣布將拆除在古巴的飛彈。
