---
title: "信度、效度：態度量表的回答模式"
image: polisci preview.svg
date: "2023-11-17"
description: Analyzing relationships and interactions among various economic elements.
categories: [politics]
format:
  html: 
    code-fold: false
citation:
  url: https://yueswater.netlify.app/posts/2023-11-17-response-styles/
---

<!-- 本篇文章是基於〈態度量表的回答模式： 以外來人口影響與兩岸統合兩題組為例〉（杜素豪，廖培珊，2007）所做成的論文筆記，旨在於紀錄讀論文的心得與學習歷程。 -->

由於在大學時期，我修習的統計學偏向理論類型，且多著墨於經濟學、計算社會科學 (computational social science)，並未接觸到社會統計相關的內容。因緣際會下，開始接觸到問卷設計的領域，因此這篇文章是開啟學習社會統計的開端。

## 一份問卷到底好不好：信度與效度的量測

在社會科學中，尤其是社會學 (sociology)、心理學 (psychology)、教育學 (pedagogy)等領域中，問卷 (questionnaire)常常是進行研究的途徑之一：透過問卷訪問受訪者，進一步客觀地驗證研究者的假說。然而，這些問卷有時並未很好地量測受訪者真實的觀點；又或者是因爲一些心理、社會等層面的因素，造成問卷無法真實反映受訪者的真實想法。為了量測問卷的良莠，我們引進了**信度 (reliability)**與**效度 (validity)**的概念。

### 信度

所謂信度，即是在評量、施測過程中，對同一個施測對象，使用相同的評量、施測工具，重複進行評量與測驗時，其評量結果相同的程度（姚開屏, 1998，p. 51)
。如果結果幾乎都能夠保持一致，則代表信度很高；反之，該問卷的信度則很低。舉例來說，今天某家民調機構受託調查民眾對於 2024 年臺灣總統大選的觀點，假設該機構對特定受訪對象進行調查，在一月作出的結果可能會與七月作出的結果有些許差異。

假設受訪者回答的實際回答分數 (actual score)記為 $x$，真實分數 (true score)為 $t$，誤差 (error)為 $e$，則三者之間的關係為
$$
\begin{align}
    x = t + e \label{eq1}\tag{1}
\end{align}
$$

因此，我們要針對實際回答分數與真實分數之間的關係進行統計上的分析與解釋。實務上，我們可以利用 Pearson 相關係數 (Pearson coefficient)進行計算，稱之為信度指標 (reliability)。令 $X = x - \bar{x}$、$T = t - \bar{t}$、$\epsilon = e - \bar{e}$，因此信度指標的計算方式為：
$$
\begin{aligned}
\rho_{XT} &= \dfrac{\sigma_{XT}}{\sigma_{X}\sigma_{T}}\\
&= \dfrac{E (XT)}{\sqrt{E (X^{2})E (T^{2})}}
\end{aligned}
$$

根據  (\ref{eq1})，我們可以將 $\rho_{xt}$ 改為下面的形式：
$$
\begin{aligned}
\rho_{XT} &= \dfrac{E[ (T + \epsilon)T]}{\sqrt{E (X^{2})E (T^{2})}}\\
&= \dfrac{E (T^2)E (T\epsilon)}{\sqrt{E (X^{2})E (T^{2})}}
\end{aligned}
$$

因為我們希望受訪者的實際回答分數要與真實分數結果一致，因此假設真實分數與誤差之間不存在相關性，即 $E (te) = 0$，則
$$
\begin{aligned}
\rho_{XT}^{2} &= \dfrac{[E (T^{2})]^{2}}{E (X^{2})E (T^{2})}\\
&= \dfrac{E (T^{2})}{E (X^{2})}\\
&= \dfrac{E[ (t-\bar{t})^{2}]}{E[ (x-\bar{x})^{2}]}\\
&= \dfrac{\sigma^{2}_{t}}{\sigma^{2}_{x}}
\end{aligned}
$$
代表信賴指標是真實分數變異數與實際回答分數變異數的比值。同樣地，從  (\ref{eq1})，我們可以改寫為
$$
\begin{aligned}
E (X^{2}) &= E[ (T + \epsilon)^2]\\
&= E (T^{2}) + 2E (T\epsilon) + E (\epsilon^{2})\\
&= E (T^{2}) + E (\epsilon^{2}) \quad  (\because E (T\epsilon) = 0)
\end{aligned}
$$

兩邊同除以 $E (X^{2})$ 可得
$$
\begin{aligned}
1 &= \dfrac{E (T^{2})}{E (X^{2})} + \dfrac{E (\epsilon^{2})}{E (X^{2})}\\
&= \rho^{2}_{XT} + \dfrac{E (\epsilon^{2})}{E (X^{2})}
\end{aligned}
$$

因此可得到下面的結果：

$$
\begin{align}
\rho^{2}_{XT} = 1 - \dfrac{E (\epsilon^{2})}{E (X^{2})}\label{eq2}\tag{2}
\end{align}
$$

不難發現根據  (\ref{eq2})，當誤差變異數佔實際分數的比例越小，亦即誤差越小，回答越一致，則信度指標的平方越高。

上面是一個簡單的介紹，在實際計算信度時，我們有不同的信度指標：[^1]

- **再測信度 (test-retest reliability)**：不同時間，相同測驗。

- **複本信度 (parallel-forms reliability)**：不同時間，不同測驗。

- **折半信度 (split-half reliability)**：相同時間，不同測驗。

### 效度

效度用於量測一份問卷的正確性與準確性的程度，白話來說就是問卷是否有效地達到原先問卷制定的目標、效果與效益。測定效度的方式基本上有四種類型（姚開屏, 1998，p. 53）：

- **內容效度 (content validity)**：詢問專家問卷內容是否有辦法問出想要的問題。

- **同時效度 (concurrent validity)**：將設計好的問卷（新方法）配合標準題目（原本的問卷）同時進行測驗，計算兩者之間的相關性。

- **預測效度 (predictive validity)**：問卷是否能夠預測未來的事件。

- **建構效度 (construct validity)**：問卷的測量結果是否與建構出的理論之假設狀態相符。

## 問卷測量誤差：回答模式初探

上面提到一份問卷的問題可能會因為設計不良，從而導致問卷無法有效測量受訪者的真實狀況；又或是因為心理、社會因素，導致受訪者的答案會產生偏差。杜素豪與廖培珊  (2007) 指出，若受訪者在答題時，儘管題目、主題之間存在差異，但仍為持相同的答題模式，稱為回答模式 (response style)。

回答模式可依照受訪者答題的情況區分為極端回答 (extreme response)、正面回答 (yeasaying)、負面回答 (naysaying)、中立回答 (middle response)或默許 (acquiescence)。以極端回答為例，Hamilton (1968) 指出，對於那些無法忍受事實被模糊化、扭曲的受訪者而言，因為個性上容易緊張或認知能力較低落等因素，在回答時多會傾向選擇極端的選項。可見回答模式將會造成問卷的系統性誤差(systematic error)，也使得問卷本身的信度、效度降低。

### 回答模式的量測

為了測量一份問卷的答題是否存在回答模式，研究者多半會採用以下幾種方式進行檢測：

#### 回答模式指標(response style index)

文章指出，Wong、Rindfleish 與 Burroughs (2003) 為了避免文字上的差異影響受訪者的回答，在問卷設計時多半採用平衡量表(balanced scale) 的方式，即盡量將問題正反敘述的文字、數目排列整齊。透過平衡量表，我們可以建構次數分配表(frequency table)，也就是列出每個選項的答案之百分比，或是藉由各題回答分數的平均數、標準差，**粗略地**判斷是否存在回答模式。

#### 統計分析(statistical analysis)

文章提到，我們可以使用**事前處理(ex ante processing)**與**事後處理(ex post processing)**避免測量誤差。事前處理指的是在問卷設計之時，應該採正反向問法、調整問題次序、增加可確認效度的問題。事後處理則是在進行態度量表分析時，刪除有回答模式嫌疑的答案。實務上，研究者通常使用以下幾種方式進行事後處理：**探索性因素分析(exploratory factor analysis)**、**Cronbach's Alpha**、**Latent Class Analysis (LCA)**等。[^2]

對於何種類型的受訪者會在答題時會有回答模式，先前的文獻多半指出該現象與人格特質、認知能力與有關。誠如上述所言，極端回答者個性上較為緊張，中立回答者可能是表達意願較低、個性猶豫不決(indecisive)。事實上，人格特質、認知能力等特性多半可以反映於受訪的社會人口特徵，即教育程度、性別、家庭收入等。

## 資料分析與結果

文章使用「台灣社會變遷基本調查計畫：四期四次國家認同組」。就變量選擇而言，性別、省籍、年齡、教育程度與社經地位被納入考量，用以偵測在這些社會人口特徵上是否存在回答模式。就問題選擇而言，為了讓分析具有互斥性，避免分析標的存在相關性，文章選擇外來人口影響與兩岸統合。

### 分析方法

文章建構回答模式指標的方式十分直觀，例如外來人口影響為五個問題，除了默許數值介於 $-1$ 到 $1$ 之間外，其他指標均介於 $0$ 到 $1$。

- 極端回答：五題中回答為 $1$ 或 $5$ 的總數除 $5$。
- 中立回答：五題中回答中間選項 $3$ 的總數除 $5$。
- 非極端回答：五題中回答為 $2$ 或 $4$ 的總數除 $5$。
- 默許回答：計算正面回答與負面回答的比例後，由前者減去後者即是默許回答。

文章的分析步驟也是簡單、直觀：先檢查包含兩個量表總共九個題目中各題回答的平均數與標準差，再利用上面建構的回答模式指標分析有效樣本中的平均數與標準差，判斷量表中的回答模式，最後則是執行九題的連續性指標之驗證性潛藏類別因素模型 (LCFA-continuous indicators) 與類別性指標之潛藏類別因素分析 (LCFA-nominal indicators)。[^3]

<!-- ## 附錄 -->

<!-- ### 潛藏類別因素分析(Latent Class Factor Analysis, LCFA) -->

<!-- Vermunt 與 Magidson (2005) 指出，由於 LCA 這項分析方法本身即是為了針對連續性資料而建立的，導致許多研究者採用此方法後，導致估計參數產生偏誤(biased)，擬合度(goodness-of-fit)也無法取信於人。也因此，Vermunt 與 Magidson 將 LCA 進行調整，變成可以用在類別資料的方法，稱為潛藏類別因素分析。 -->

<!-- 不過，許多事情都是需要取捨的。LCFA 的缺點就是模型的估計參數難以解釋。為了解決上述問題，Vermunt 與 Magidson 提出將最大概似法(maximum likelihood)估計式以線性逼近(linear approximation)的方式進行解釋。 -->

<!-- 令 $\pmb{\theta}$ 代表擁有 $L$ 個潛藏變數(latent variables)的向量，$\mathbf{y}$ 則代表 $K$ 個變觀察變數(observed variables)的向量，並以 $l$ 與 $k$ 代表特定的潛藏與觀察變數。因此，潛藏變量模型可以寫成： -->
<!-- $$ -->
<!-- f(\pmb{\theta}, \mathbf{y}) = f(\pmb{\theta})f(\mathbf{y}|\pmb{\theta}) = f(\pmb{\theta})\prod_{k = 1}^{K}f(y_{k}|\pmb{\theta}) -->
<!-- $$ -->

[^1]: 詳細推導請參考附錄。
[^2]: Cronbach's Alpha 的計算方式請參見附錄。
[^3]: 關於潛藏類別分析的說明請見附錄。






