---
title: "聊聊失敗這件事"
date: "2021-02-04"
categories: [taiwan, education, experience]
---

這個主題是我根據最近的事情，以及自身過往的經驗撰寫。

轉學考說明會落幕已久，近期也致力於輔導有意準備轉學考的學弟妹們。在與他們談話當中，我看到他們對於「失敗」的不安、對於「挫折」的恐懼，深怕自己在備考過程中，沒有準備的完善、考試當天自身狀況不佳、認為自己並沒有那麼聰明爾爾。面對他們的情緒，我只好一一的講述我的故事給他們聽。

國中時，我並不是一個熱愛讀書的學生（現在也不是，但相較之前好多了），這邊指涉的讀書是指「為了得到成績而研讀某些領域」之行為，那時候認為，一昧的為了成績向前看是一件愚蠢的事情，所以我在會考時並沒有盡自己太大的努力，想當然也沒有考上彼時對於自己所要求的前三志願。

高中時，我因為國文太過枯燥乏味，因此選擇放棄花時間讀國文，導致國文成績一落千丈，學測與指考的表現也是差強人意。不過在那時，我對於讀書這件事有些改觀，心想：如果要上台大、政大的話，勢必還是要讀點書的。但最後的結果卻是，因為我那時的玩心還是太重，連對自己最低要求的中字輩都擦不上邊，最終成為南漂學子。

因為之前的大學與科系並非我心之所向，在那裡我也過的不甚愉快，原因是因為文學作品充其量只能夠作為我休閒時光之消遣，無法成為我的主修科目，那樣太痛苦了。於是在第一次轉學考失敗之後，便毅然決然的決定要考取一直以來都想要就讀的科系——政治學系。最後，經過了一年的拼搏與努力，在堅持夢想之下，我來到了公館讀書。

是的，我失敗了無數次，最終有了成果。但這代表著什麼嗎？或許很多人會認為，我能考上就表示我真的很厲害，未來必能成為國家之棟樑。然而，這一切只是被外表蒙蔽所得出之結論罷。

其實，在準備考試的期間，我真的多次想要放棄自己，想要放棄這段讓我痛苦、疲憊不堪的日子，當時心裡想的，只有兩個：「我好想考上」跟「我好累」。在這些日子裡，我的父母、親朋好友都相繼來勸我別考了，好好的讀英文系吧！但我也不知道為什麼，自己心裡就有一股衝動與執念，想要將這段與考試的關係有始有終。

在2020年7月11日於台大應試那天，我悟出了道理。

或許對我自己在追求夢想的過程中，投注的精力與時間不容我犯下任何錯誤，但很明顯的，直到這天之前，我都不清楚自己到底錯在哪、對在哪，只是像隻無頭蒼蠅一樣往前衝。其實，那時候悟出的道理，也只不過是用來安慰我當時激憤與悲痛的心靈，並不是什麼人生大道理。但現在回頭過來，似乎是有些邏輯存在的。

努力，這個字的定義太過於沈重，我甚至無法明確的勾勒出它的輪廓。然而，備考的日子讓我了解了。努力並不是一個結果，而是過程，在這段過程中學習到的任何東西並非無用武之地，所謂養兵千日用於一時，即是這個道理。我很難相信，之前在英文系學習的語音學、語言學、文學作品導讀、發音練習能夠對我人生有益處；直到我最近在補習班輔導時，學生問到的問題都能夠透過之前在英文系學習的知識、工具迎刃而解。

同時，在之前的時間，我開始學會與自己獨處，開始學會如何讓自己面對難題的時候，把焦慮化為動力、把痛苦作為補給，一步步地將事情梳理出一定的架構，並以有效率以及有效的方式處理。

相信每個人都有面臨失敗與挫折的經歷，但最重要的是要怎樣定義失敗。對我而言，失敗只是過程的一小部分，追逐還在持續，而夢想尚在遠方，我所企及的是在過程中能夠得到的任何東西，作為滋養我這個人的養分。

願每個身在考試、挫折的人能夠正視自己所面對的難題，慢慢琢磨解決方法。

在黎明來臨前，我們總有個療傷的夜晚。

**※對我轉學考準備方式有興趣的人可以參考[這篇文章](https://www.pttweb.cc/bbs/Transfer/M.1597806925.A.381?fbclid=IwAR3ie-g8gqjTg75KIdI7rJqFCVbVjwrNc-qVgU9MJbOGdKI5bqeqXAf7VnM)。**