---
title: "組織性行為模型(Organizational Behavior Model, OBM)"
date: "2023-03-24"
categories: [polisci, foreign policy]
---

OBM 認為組織內部的決策制定乃至執行是被分割的，而非單一行為者強調決策制定和執行，尤其是執行環節的重要性。可以發現 RAM 較不注重政策執行的環節，但同 OBM 一樣重視政策制定。不同於 RAM，OBM 解釋的行為主體是組織本身，而非個人或整個政府，對其行為的理解將從組織性的目的與組織成員的共同實踐出發。

## 基本概念：

- 組織即是在共同目標下，內部成員各自分工（division of labor），各自發揮既定功能與扮演一定的角色，形成組織內的次級組織或次級單位，最終構成巨大的集合體(conglomerate)。
- 在上述分工型態下，組織整體從決策制定到決策的執行，實際上是被分割為每個次級組織內的工作和程序。所有次級組織各自完成其工作與任務後，便共同形成組織的整體產出（output）。政府多數的決策，其制定和執行的具體行動，實際上就是從次級組織到組織整體從分工到協作的組織產出(organizational output)。

在上述前提下，往往出現 factored problem 以及 fractionated power。

### 標準作業程序（standard operation procedure，SOP）

由於政府內各次級組織長期所擔負的是一定範圍和本質的工作與業務一也就是一定性質的政策問題一所以每個單位、部門、次級組織，長期而言會將其如何處理這些既定政策問題時，從界定問題、評估選項，到選擇方案與執行政策，都逐漸發展出一套標準化的做法和程序，這就是所謂的SOP。與SOP類似的概念是指令程d序(program)、常規(routine)、劇碼(repertoire)的貯藏庫或行動劇本。換言之，**組織目前在決策與執行上的行為，往往能以已往其曾經產生的行為來理解和預測**。而 OBM 所強調的SOP，實際上與 RAM 所強調的工具理性有共通之處——SOP其實是將工具理性，內化到組織之中，成為組織的記憶。

### 組織文化與妥適性邏輯

當SOP行之既久，那麽在SOP的實際行為背後，往往也會發展出一套合理化、固定化該SOP的理念、價值、規範基礎，這些規範也就是組織文化。所以，要解釋為何組織重複出現SOP的這套行為、程序，其關鍵往往不只是工具理性（logic of efficiency）的內化，而更在於必須符合既定的規範、價值、組織文化，也就是 logic of appropriateness。

根據 Paul DiMaggio 和 Walter Powell 的研究，其解釋了組織的內涵與行為邏輯：

1. 組織偏好之衍生：將研究焦點放在行動理論和基層官僚上，利益實際上從決定中推導出來。行動是組織定義其所欲和將為的時機，這些慾望通常內生於組織，而非外源性。
2. 組織行為限制理性：其著重組織如何努力爭取正當性、地位和理念，這些理念對於組織內部或是
同一個組織場域內部而非組織外部的人更為重要。
3. 組織結構特異：這些非正式結構受到新興、較不明顯的主宰者所渴望，可能會顛覆組織原初創立者為了完成目標所設置的正式結構。
4. 組織如何將自身連繫到所處之環境：利益包括場域的需要和努力拉攏機構的利益團體，而文化則是組織和某個部門或是領域的關係，而不是某個特別的地理場域。換句話說，和居住在同一城市的一般老百姓比較起來，一
名休士頓的警官可能和芝加哥的警官間有更高的共同性。

### 推論模式：預測

OBM 認為，對於一個組織行為在特定時點 $t$ 的最佳解釋在 $t-1$，而對於即將在 $t+1$ 發生所做的最佳預測在 $t$，可見 OBM 係對於事件進行預測，目的在於揭露特殊的能力、劇碼和組織常規。

組織的能力會影響政府的選擇，具有特定能力的組織更可能被選定來處理相關事務。同時，組織的優先順序會影響行動的實施，需要權衡取捨。組織的行動常受常規影響，而非完全受政府領導者指示。領導者若忽略行政可行性的考量，可能自食其果，其通常呈現有限彈性和漸進改變，且受組織常規影響。另外，
長期計畫在應對危機時扮演重要角色。

### 小結

所以，組織的行為往往是**相對穩定**，但是**帶有惰性的**，組織行為要發生變革，並不常見，多半在一定條件下才會產生。而且，組織從偏好到資源（預算）與行為的變革，多半都是漸進(incremental)的。

因此國家面對必須改變的外交、國際狀態時，要端視各個次級組織如何應對、思考問題，最後加總起來。在組織內部因每個部門均為各自行事、分工，僅能關注到自身部門負責的部分；次級組織面臨到的問題永遠都是類似的狀況，因此出現 SOP 應對相似的問題。

## 以 OBM 解釋古巴飛彈危機

以下我們將使用 OBM 回答古巴飛彈危機的三個主要問題：

1. 蘇聯在古巴部屬攻擊性飛彈
2. 美國對古巴進行封鎖
3. 蘇聯從古巴撤除飛彈

### 蘇聯在古巴部署飛彈的政策執行

蘇聯在古巴部署飛彈，從決策到在古巴完成部署可實際啟動的飛彈，整個過程包含許多環節，也經過層層授權。這種與核彈相關的行動屬於最高機密，嚴禁洩漏，因此在重重保密下，各個授權單位之間並不清楚整體計畫之內涵。當武器運送到裝設地點後，執行單位就交接給當地的蘇聯軍隊，由 Issa Pliyev 將軍指揮。

上述前提就是造成 Pliyev 與其副手及部屬相處極不融洽、執行團隊內部充斥爭議與相互指責的原因，造成許多事前做好的縝密規劃，包含 SOP 之可能調整都未能落實。飛彈部隊的工兵被要求在一定期限內完工，但 Pliyev 的副手們並未盡責監督。

莫斯科派遣的 Anatoly Gribkov 將軍抵達古巴檢查執行進度時，Pliyev 告知美國 U-2 偵察機已經飛越上空，但並未報告給莫斯科，也未改變 SOP。

### 美國對古巴的封鎖

1962年10月22日下午7點，甘迺迪對全國發佈電視聲明，表示已經發現位於古巴的蘇聯飛彈，並且呼籲蘇聯立即撤除飛彈。同時將進行攻撃性武器裝備的封鎖禁運。原則上只封鎖運往古巴的戰備武器，對生活必需品以及燃料運輸則不加管制，以免蘇聯對柏林進行相同的封鎖。整個行動由海軍執行，在正式確認封鎖之前，國防部長 McNarmara 便開始規劃任務執行藍圖。當然，總統對封鎖的作法也有一些意見。對海軍而言希望能放手完成這項軍事任務，對總統而言，他希望藉此調整情勢，給蘇聯時間去思索因應。

對美國海軍而言，**執行封鎖並無既存的 SOP 可資參考遵循**，所以如何執行封鎖，在美國內部有不同的意見與不確定性。此時，海軍採用新的指揮方式，這是美國歷史上已往從未出現過的程序和模式：由政治領導人直接指揮第一線人員；總統坐鎮白宮，直接和封鎖線上值勤的艦艇指揮官聯繫，以求控制全局以及避免不必要的衝突。10月21日國安會議，海軍指揮官 George Anderson 上將報告封鎖與發生衝突的 SOP。Anderson 建議封鎖命令施以緩衝期，使莫斯科有時間指示其商船等如何因應，其論點獲得 McNarmara 的贊成。

10月23日，JFK 同意在10月24日再開始實施封鎖。McNarmara 建議欄檢半徑訂在以古巴為中心 800 英哩，剛好超過 IL-28 轟炸機的範圍，也遠超過 MiG-21 戰機的監控。第一艘攜帶武器的蘚聯船艦 Kimovsk 即將在10月23到24日之間的午夜穿過封鎖線，美方希望在23日天黑之前攔下這艘船，McNarmara認為應該讓第一線的指揮官有自主迴旋的空間見機行事，JFK 此時表示同意。

10月23 日晚上：甘迺迪與英國使節 David Ormsby-Gore 重新檢視計畫後，JFK 決定將封鎖半徑縮小為500英哩。第一艘蘇聯船艦在10月24日早上抵達新的封鎖線並且在千鈞一髪之際掉頭離開。實際上海軍第一線指揮官並沒有SOP的束縛，而有某種自主空間，這使得整個封鎖行動不見得是在符合ModelI的假設一能控制所有條件、預見每個行動的後果一之下去執行的。沒有SOP的封鎖執行，最後並未導致衝突爆發，並不是美方事先能完全掌控預料到的。




